version: "3.8"
services:
  up-rugby:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    container_name: up-rugby_container
    env_file:
      - .env.local
    volumes:
      - ./:/app
    restart: always
    ports:
      - 3000:3000
    networks:
      - up-rugby_network

  maildev:
    image: maildev/maildev
    restart: always
    environment:
      - TZ=Europe/Paris
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - up-rugby_network
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  stripe-listen:
    image: stripe/stripe-cli
    env_file:
      - .env.local
    command: listen --forward-to http://up-rugby_container:3000/api/stripe/webhook
    networks:
      - up-rugby_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  up-rugby_network:
    external: true
